# version: 2.1

# orbs:
#   aws-ecr: circleci/aws-ecr@8.0.0
#   aws-ecs: circleci/aws-ecs@2.2.0

# jobs:
#   deploy:
#     docker:
#       - image: cimg/aws:2023.09
#     steps:
#       - checkout
#       - aws-ecs/update-service:
#           family: "your-ecs-task-definition-name"
#           cluster-name: "mycluster"
#           service-name: "my-ecs-service2"
#           container-image-name-updates: "container=public.ecr.aws/w1g6z4w3/repo:latest"
#           aws-region: $AWS_REGION

# workflows:
#   deploy-workflow:
#     jobs:
#       - deploy:
#           context: aws-creds  # CircleCI context containing AWS credentials



#################################################


# version: 2.1

# orbs:
#   terraform: circleci/terraform@3.2.0

# jobs:
#   terraform_apply:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - terraform/install:
#           terraform_version: "1.3.7"
#       - run:
#           name: Terraform Init
#           command: terraform init
#       - run:
#           name: Terraform Plan
#           command: terraform plan
#       - run:
#           name: Terraform Apply
#           command: terraform apply -auto-approve

# workflows:
#   terraform:
#     jobs:
#       - terraform_apply:
#           context: aws-creds # Optional: If you're using CircleCI contexts for credentials

################################################################

version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0
  aws-cli: circleci/aws-cli@4.0.0  # For AWS CLI setup (but credentials are passed via env vars)

jobs:
  terraform_apply:
    docker:
      - image: cimg/aws:2024.01  # Includes AWS CLI & Terraform
    environment:
      AWS_REGION: "us-east-1"  # Set default region (or use env var)
    steps:
      - checkout
      - aws-cli/setup  # No direct args; relies on env vars
      - terraform/install:
          terraform_version: "1.3.7"
      - run:
          name: Terraform Init
          command: terraform init -input=false
      - run:
          name: Terraform Plan (Save Output)
          command: terraform plan -out=tfplan
      - run:
          name: Terraform Apply
          command: terraform apply -input=false -auto-approve tfplan
      - store_artifacts:
          path: tfplan

workflows:
  terraform_workflow:
    jobs:
      - terraform_apply:
          context: aws-creds  # Contains AWS credentials as env vars
          filters:
            branches:
              only: main
